/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.ContinueWithRecoveryUi
import org.openapitools.client.models.ContinueWithRecoveryUiFlow
import org.openapitools.client.models.ContinueWithRedirectBrowserTo
import org.openapitools.client.models.ContinueWithSetOrySessionToken
import org.openapitools.client.models.ContinueWithSettingsUi
import org.openapitools.client.models.ContinueWithVerificationUi

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*
import kotlinx.serialization.json.JsonClassDiscriminator

/**
 * 
 *
 * @param action Action will always be `redirect_browser_to` redirect_browser_to ContinueWithActionRedirectBrowserToString
 */
@Serializable(with = ContinueWithDeserializer::class)
sealed class ContinueWith {

    /* Action will always be `redirect_browser_to` redirect_browser_to ContinueWithActionRedirectBrowserToString */
    @SerialName(value = "action") @Required abstract val action: ContinueWith.Action

    /**
     * Action will always be `redirect_browser_to` redirect_browser_to ContinueWithActionRedirectBrowserToString
     *
     * Values: redirect_browser_to
     */
    @Serializable
    enum class Action(val value: kotlin.String) {
        @SerialName(value = "redirect_browser_to") redirect_browser_to("redirect_browser_to"),
        @SerialName(value = "set_ory_session_token") set_ory_session_token("set_ory_session_token"),
        @SerialName(value = "show_settings_ui") show_settings_ui("show_settings_ui"),
        @SerialName(value = "show_verification_ui") show_verification_ui("show_verification_ui"),
        @SerialName(value = "show_recovery_ui") show_recovery_ui("show_recovery_ui");
    }

}

