/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.Provider

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Contains a list of all available FedCM providers.
 *
 * @param csrfToken 
 * @param providers 
 */
@Serializable

data class CreateFedcmFlowResponse (

    @SerialName(value = "csrf_token") val csrfToken: kotlin.String? = null,

    @SerialName(value = "providers") val providers: kotlin.collections.List<Provider>? = null

) {


}

