/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.IdentityWithCredentialsPasswordConfig

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Create Identity and Import Password Credentials
 *
 * @param config 
 */
@Serializable

data class IdentityWithCredentialsPassword (

    @SerialName(value = "config") val config: IdentityWithCredentialsPasswordConfig? = null

) {


}

