/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.*

/**
 * The experimental state represents the state of a login flow. This field is EXPERIMENTAL and subject to change!
 *
 * Values: choose_method,sent_email,passed_challenge
 */
@Serializable
enum class LoginFlowState(val value: kotlin.String) {

    @SerialName(value = "choose_method")
    choose_method("choose_method"),

    @SerialName(value = "sent_email")
    sent_email("sent_email"),

    @SerialName(value = "passed_challenge")
    passed_challenge("passed_challenge");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: LoginFlowState?): kotlin.String? = if (data is LoginFlowState) "$data" else null

        /**
         * Returns a valid [LoginFlowState] for [data], null otherwise.
         */
        fun decode(data: LoginFlowState?): LoginFlowState? = data?.let {
          val normalizedData = "$it".lowercase()
          values().firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}


