/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param clientId The RP's client identifier, issued by the IdP.
 * @param configUrl A full path of the IdP config file.
 * @param domainHint By specifying one of domain_hints values provided by the accounts endpoints, the FedCM dialog selectively shows the specified account.
 * @param fields Array of strings that specifies the user information (\"name\", \" email\", \"picture\") that RP needs IdP to share with them.  Note: Field API is supported by Chrome 132 and later.
 * @param loginHint By specifying one of login_hints values provided by the accounts endpoints, the FedCM dialog selectively shows the specified account.
 * @param nonce A random string to ensure the response is issued for this specific request. Prevents replay attacks.
 * @param parameters Custom object that allows to specify additional key-value parameters: scope: A string value containing additional permissions that RP needs to request, for example \" drive.readonly calendar.readonly\" nonce: A random string to ensure the response is issued for this specific request. Prevents replay attacks.  Other custom key-value parameters.  Note: parameters is supported from Chrome 132.
 */
@Serializable

data class Provider (

    /* The RP's client identifier, issued by the IdP. */
    @SerialName(value = "client_id") val clientId: kotlin.String? = null,

    /* A full path of the IdP config file. */
    @SerialName(value = "config_url") val configUrl: kotlin.String? = null,

    /* By specifying one of domain_hints values provided by the accounts endpoints, the FedCM dialog selectively shows the specified account. */
    @SerialName(value = "domain_hint") val domainHint: kotlin.String? = null,

    /* Array of strings that specifies the user information (\"name\", \" email\", \"picture\") that RP needs IdP to share with them.  Note: Field API is supported by Chrome 132 and later. */
    @SerialName(value = "fields") val fields: kotlin.collections.List<kotlin.String>? = null,

    /* By specifying one of login_hints values provided by the accounts endpoints, the FedCM dialog selectively shows the specified account. */
    @SerialName(value = "login_hint") val loginHint: kotlin.String? = null,

    /* A random string to ensure the response is issued for this specific request. Prevents replay attacks. */
    @SerialName(value = "nonce") val nonce: kotlin.String? = null,

    /* Custom object that allows to specify additional key-value parameters: scope: A string value containing additional permissions that RP needs to request, for example \" drive.readonly calendar.readonly\" nonce: A random string to ensure the response is issued for this specific request. Prevents replay attacks.  Other custom key-value parameters.  Note: parameters is supported from Chrome 132. */
    @SerialName(value = "parameters") val parameters: kotlin.collections.Map<kotlin.String, kotlin.String>? = null

) {


}

