/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.UiNodeAnchorAttributes
import org.openapitools.client.models.UiNodeImageAttributes
import org.openapitools.client.models.UiNodeInputAttributes
import org.openapitools.client.models.UiNodeScriptAttributes
import org.openapitools.client.models.UiNodeTextAttributes
import org.openapitools.client.models.UiText

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*
import kotlinx.serialization.json.JsonClassDiscriminator
import kotlinx.serialization.json.JsonElement

/**
 * @param nodeType NodeType represents this node's types. It is a mirror of `node.type` and is primarily used to allow compatibility with OpenAPI 3.0. In this struct it technically always is \"script\". text Text input Input img Image a Anchor script Script
 * @param `value` The input's value.
 */
@Serializable(with = UiNodeAttributesDeserializer::class)
sealed class UiNodeAttributes {

    /* NodeType represents this node's types. It is a mirror of `node.type` and is primarily used to allow compatibility with OpenAPI 3.0. In this struct it technically always is \"script\". text Text input Input img Image a Anchor script Script */
    @SerialName(value = "node_type") @Required abstract val nodeType: UiNodeAttributes.NodeType

    /**
     * NodeType represents this node's types. It is a mirror of `node.type` and is primarily used to allow compatibility with OpenAPI 3.0. In this struct it technically always is \"script\". text Text input Input img Image a Anchor script Script
     *
     * Values: text,input,img,a,script
     */
    @Serializable
    enum class NodeType(val value: kotlin.String) {
        @SerialName(value = "text") text("text"),
        @SerialName(value = "input") input("input"),
        @SerialName(value = "img") img("img"),
        @SerialName(value = "a") a("a"),
        @SerialName(value = "script") script("script");
    }
    /**
     * The autocomplete attribute for the input. email InputAttributeAutocompleteEmail tel InputAttributeAutocompleteTel url InputAttributeAutocompleteUrl current-password InputAttributeAutocompleteCurrentPassword new-password InputAttributeAutocompleteNewPassword one-time-code InputAttributeAutocompleteOneTimeCode
     *
     * Values: email,tel,url,currentMinusPassword,newMinusPassword,oneMinusTimeMinusCode
     */
    @Serializable
    enum class Autocomplete(val value: kotlin.String) {
        @SerialName(value = "email") email("email"),
        @SerialName(value = "tel") tel("tel"),
        @SerialName(value = "url") url("url"),
        @SerialName(value = "current-password") currentMinusPassword("current-password"),
        @SerialName(value = "new-password") newMinusPassword("new-password"),
        @SerialName(value = "one-time-code") oneMinusTimeMinusCode("one-time-code");
    }
    /**
     * OnClickTrigger may contain a WebAuthn trigger which should be executed on click.  The trigger maps to a JavaScript function provided by Ory, which triggers actions such as PassKey registration or login. oryWebAuthnRegistration WebAuthnTriggersWebAuthnRegistration oryWebAuthnLogin WebAuthnTriggersWebAuthnLogin oryPasskeyLogin WebAuthnTriggersPasskeyLogin oryPasskeyLoginAutocompleteInit WebAuthnTriggersPasskeyLoginAutocompleteInit oryPasskeyRegistration WebAuthnTriggersPasskeyRegistration oryPasskeySettingsRegistration WebAuthnTriggersPasskeySettingsRegistration
     *
     * Values: oryWebAuthnRegistration,oryWebAuthnLogin,oryPasskeyLogin,oryPasskeyLoginAutocompleteInit,oryPasskeyRegistration,oryPasskeySettingsRegistration
     */
    @Serializable
    enum class OnclickTrigger(val value: kotlin.String) {
        @SerialName(value = "oryWebAuthnRegistration") oryWebAuthnRegistration("oryWebAuthnRegistration"),
        @SerialName(value = "oryWebAuthnLogin") oryWebAuthnLogin("oryWebAuthnLogin"),
        @SerialName(value = "oryPasskeyLogin") oryPasskeyLogin("oryPasskeyLogin"),
        @SerialName(value = "oryPasskeyLoginAutocompleteInit") oryPasskeyLoginAutocompleteInit("oryPasskeyLoginAutocompleteInit"),
        @SerialName(value = "oryPasskeyRegistration") oryPasskeyRegistration("oryPasskeyRegistration"),
        @SerialName(value = "oryPasskeySettingsRegistration") oryPasskeySettingsRegistration("oryPasskeySettingsRegistration");
    }
    /**
     * OnLoadTrigger may contain a WebAuthn trigger which should be executed on load.  The trigger maps to a JavaScript function provided by Ory, which triggers actions such as PassKey registration or login. oryWebAuthnRegistration WebAuthnTriggersWebAuthnRegistration oryWebAuthnLogin WebAuthnTriggersWebAuthnLogin oryPasskeyLogin WebAuthnTriggersPasskeyLogin oryPasskeyLoginAutocompleteInit WebAuthnTriggersPasskeyLoginAutocompleteInit oryPasskeyRegistration WebAuthnTriggersPasskeyRegistration oryPasskeySettingsRegistration WebAuthnTriggersPasskeySettingsRegistration
     *
     * Values: oryWebAuthnRegistration,oryWebAuthnLogin,oryPasskeyLogin,oryPasskeyLoginAutocompleteInit,oryPasskeyRegistration,oryPasskeySettingsRegistration
     */
    @Serializable
    enum class OnloadTrigger(val value: kotlin.String) {
        @SerialName(value = "oryWebAuthnRegistration") oryWebAuthnRegistration("oryWebAuthnRegistration"),
        @SerialName(value = "oryWebAuthnLogin") oryWebAuthnLogin("oryWebAuthnLogin"),
        @SerialName(value = "oryPasskeyLogin") oryPasskeyLogin("oryPasskeyLogin"),
        @SerialName(value = "oryPasskeyLoginAutocompleteInit") oryPasskeyLoginAutocompleteInit("oryPasskeyLoginAutocompleteInit"),
        @SerialName(value = "oryPasskeyRegistration") oryPasskeyRegistration("oryPasskeyRegistration"),
        @SerialName(value = "oryPasskeySettingsRegistration") oryPasskeySettingsRegistration("oryPasskeySettingsRegistration");
    }

}

