/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.UpdateRecoveryFlowWithCodeMethod
import org.openapitools.client.models.UpdateRecoveryFlowWithLinkMethod

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*
import kotlinx.serialization.json.JsonClassDiscriminator

/**
 * Update Recovery Flow Request Body
 *
 * @param email The email address of the account to recover  If the email belongs to a valid account, a recovery email will be sent.  If you want to notify the email address if the account does not exist, see the [notify_unknown_recipients flag](https://www.ory.sh/docs/kratos/self-service/flows/account-recovery-password-reset#attempted-recovery-notifications)  If a code was already sent, including this field in the payload will invalidate the sent code and re-send a new code.  format: email
 * @param method Method is the method that should be used for this recovery flow  Allowed values are `link` and `code`. link RecoveryStrategyLink code RecoveryStrategyCode
 * @param csrfToken Sending the anti-csrf token is only required for browser login flows.
 * @param transientPayload Transient data to pass along to any webhooks
 * @param code Code from the recovery email  If you want to submit a code, use this field, but make sure to _not_ include the email field, as well.
 */
@Serializable


@OptIn(ExperimentalSerializationApi::class)
@JsonClassDiscriminator(discriminator = "method")
sealed class UpdateRecoveryFlowBody {

    /* Method is the method that should be used for this recovery flow  Allowed values are `link` and `code`. link RecoveryStrategyLink code RecoveryStrategyCode */
    @SerialName(value = "method") @Required abstract val method: UpdateRecoveryFlowBody.Method
    /**
     * Method is the method that should be used for this recovery flow  Allowed values are `link` and `code`. link RecoveryStrategyLink code RecoveryStrategyCode
     *
     * Values: link,code
     */
    @Serializable
    enum class Method(val value: kotlin.String) {
        @SerialName(value = "link") link("link"),
        @SerialName(value = "code") code("code");
    }

}

