/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.UpdateLoginFlowWithCodeMethod
import org.openapitools.client.models.UpdateLoginFlowWithIdentifierFirstMethod
import org.openapitools.client.models.UpdateLoginFlowWithLookupSecretMethod
import org.openapitools.client.models.UpdateLoginFlowWithOidcMethod
import org.openapitools.client.models.UpdateLoginFlowWithPasskeyMethod
import org.openapitools.client.models.UpdateLoginFlowWithPasswordMethod
import org.openapitools.client.models.UpdateLoginFlowWithTotpMethod
import org.openapitools.client.models.UpdateLoginFlowWithWebAuthnMethod

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*
import kotlinx.serialization.json.JsonClassDiscriminator

/**
 * @param method Method should be set to \"password\" when logging in using the identifier and password strategy.
 */

@Serializable(with = UpdateLoginFlowBodyDeserializer::class)
sealed class UpdateLoginFlowBody {

    /* Method should be set to \"password\" when logging in using the identifier and password strategy. */
    @SerialName(value = "method") @Required abstract val method: kotlin.String
}

