/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param csrfToken CSRFToken is the anti-CSRF token.
 * @param token Token contains the result of `navigator.credentials.get`.
 * @param nonce Nonce is the nonce that was used in the `navigator.credentials.get` call. If specified, it must match the `nonce` claim in the token.
 */
@Serializable

data class UpdateFedcmFlowBody (

    /* CSRFToken is the anti-CSRF token. */
    @SerialName(value = "csrf_token") @Required val csrfToken: kotlin.String,

    /* Token contains the result of `navigator.credentials.get`. */
    @SerialName(value = "token") @Required val token: kotlin.String,

    /* Nonce is the nonce that was used in the `navigator.credentials.get` call. If specified, it must match the `nonce` claim in the token. */
    @SerialName(value = "nonce") val nonce: kotlin.String? = null

) {


}

