/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.UpdateRegistrationFlowWithCodeMethod
import org.openapitools.client.models.UpdateRegistrationFlowWithOidcMethod
import org.openapitools.client.models.UpdateRegistrationFlowWithPasskeyMethod
import org.openapitools.client.models.UpdateRegistrationFlowWithPasswordMethod
import org.openapitools.client.models.UpdateRegistrationFlowWithProfileMethod
import org.openapitools.client.models.UpdateRegistrationFlowWithWebAuthnMethod

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*
import kotlinx.serialization.json.JsonClassDiscriminator

/**
 * Update Registration Request Body
 *
 * @param method Method  Should be set to profile when trying to update a profile.
 * @param code The OTP Code sent to the user

 */
@Serializable


@OptIn(ExperimentalSerializationApi::class)
@JsonClassDiscriminator(discriminator = "method")
sealed class UpdateRegistrationFlowBody {

    /* Method  Should be set to profile when trying to update a profile. */
    @SerialName(value = "method") @Required abstract val method: kotlin.String
    /**
     * Screen requests navigation to a previous screen.  This must be set to credential-selection to go back to the credential selection screen. credential-selection RegistrationScreenCredentialSelection nolint:gosec // not a credential previous RegistrationScreenPrevious
     *
     * Values: credentialMinusSelection,previous
     */
    @Serializable
    enum class Screen(val value: kotlin.String) {
        @SerialName(value = "credential-selection") credentialMinusSelection("credential-selection"),
        @SerialName(value = "previous") previous("previous");
    }

}

