/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.UpdateSettingsFlowWithLookupMethod
import org.openapitools.client.models.UpdateSettingsFlowWithOidcMethod
import org.openapitools.client.models.UpdateSettingsFlowWithPasskeyMethod
import org.openapitools.client.models.UpdateSettingsFlowWithPasswordMethod
import org.openapitools.client.models.UpdateSettingsFlowWithProfileMethod
import org.openapitools.client.models.UpdateSettingsFlowWithTotpMethod
import org.openapitools.client.models.UpdateSettingsFlowWithWebAuthnMethod

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*
import kotlinx.serialization.json.JsonClassDiscriminator

/**
 * Update Settings Flow Request Body
 *
 * @param method Method  Should be set to \"passkey\" when trying to add, update, or remove a webAuthn pairing.
 */
@Serializable


@OptIn(ExperimentalSerializationApi::class)
@JsonClassDiscriminator(discriminator = "method")
sealed class UpdateSettingsFlowBody {

    /* Method  Should be set to \"passkey\" when trying to add, update, or remove a webAuthn pairing. */
    @SerialName(value = "method") @Required abstract val method: kotlin.String

}

