/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package sh.ory.model


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param attribute 
 * @param condition 
 * @param `value` 
 */
@Serializable

data class AttributeFilter (

    @SerialName(value = "attribute") val attribute: kotlin.String? = null,

    @SerialName(value = "condition") val condition: AttributeFilter.Condition? = null,

    @SerialName(value = "value") val `value`: kotlin.String? = null

) {

    /**
     * 
     *
     * Values: EQUALS,NOT_EQUALS,CONTAINS,NOT_CONTAINS,REGEX,NOT_REGEX,SET,NOT_SET
     */
    @Serializable
    enum class Condition(val value: kotlin.String) {
        @SerialName(value = "equals") EQUALS("equals"),
        @SerialName(value = "not_equals") NOT_EQUALS("not_equals"),
        @SerialName(value = "contains") CONTAINS("contains"),
        @SerialName(value = "not_contains") NOT_CONTAINS("not_contains"),
        @SerialName(value = "regex") REGEX("regex"),
        @SerialName(value = "not_regex") NOT_REGEX("not_regex"),
        @SerialName(value = "set") SET("set"),
        @SerialName(value = "not_set") NOT_SET("not_set");
    }
}

