/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package sh.ory.model

import sh.ory.model.ContinueWithRecoveryUi
import sh.ory.model.ContinueWithRecoveryUiFlow
import sh.ory.model.ContinueWithSetOrySessionToken
import sh.ory.model.ContinueWithSettingsUi
import sh.ory.model.ContinueWithVerificationUi

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param action Action will always be `show_recovery_ui` show_recovery_ui ContinueWithActionShowRecoveryUIString
 * @param flow 
 * @param orySessionToken Token is the token of the session
 */


interface ContinueWith {

    /* Action will always be `show_recovery_ui` show_recovery_ui ContinueWithActionShowRecoveryUIString */
    @SerialName(value = "action") @Required val action: ContinueWith.Action
    @SerialName(value = "flow") @Required val flow: ContinueWithRecoveryUiFlow
    /* Token is the token of the session */
    @SerialName(value = "ory_session_token") @Required val orySessionToken: kotlin.String
    /**
     * Action will always be `show_recovery_ui` show_recovery_ui ContinueWithActionShowRecoveryUIString
     *
     * Values: SHOW_RECOVERY_UI
     */
    @Serializable
    enum class Action(val value: kotlin.String) {
        @SerialName(value = "show_recovery_ui") SHOW_RECOVERY_UI("show_recovery_ui");
    }
}

