/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package sh.ory.model

import sh.ory.model.ContinueWithVerificationUiFlow

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Indicates, that the UI flow could be continued by showing a verification ui
 *
 * @param action Action will always be `show_verification_ui` set_ory_session_token ContinueWithActionSetOrySessionToken show_verification_ui ContinueWithActionShowVerificationUI
 * @param flow 
 */
@Serializable

data class ContinueWithVerificationUi (

    /* Action will always be `show_verification_ui` set_ory_session_token ContinueWithActionSetOrySessionToken show_verification_ui ContinueWithActionShowVerificationUI */
    @SerialName(value = "action") @Required val action: ContinueWithVerificationUi.Action,

    @SerialName(value = "flow") @Required val flow: ContinueWithVerificationUiFlow

) {

    /**
     * Action will always be `show_verification_ui` set_ory_session_token ContinueWithActionSetOrySessionToken show_verification_ui ContinueWithActionShowVerificationUI
     *
     * Values: SET_ORY_SESSION_TOKEN,SHOW_VERIFICATION_UI
     */
    @Serializable
    enum class Action(val value: kotlin.String) {
        @SerialName(value = "set_ory_session_token") SET_ORY_SESSION_TOKEN("set_ory_session_token"),
        @SerialName(value = "show_verification_ui") SHOW_VERIFICATION_UI("show_verification_ui");
    }
}

