/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package sh.ory.model

import sh.ory.model.ContinueWithSetOrySessionToken
import sh.ory.model.ContinueWithVerificationUi
import sh.ory.model.ContinueWithVerificationUiFlow

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param action Action will always be `set_ory_session_token` set_ory_session_token ContinueWithActionSetOrySessionToken show_verification_ui ContinueWithActionShowVerificationUI
 * @param flow 
 * @param orySessionToken Token is the token of the session
 */


interface ContinueWith {

    /* Action will always be `set_ory_session_token` set_ory_session_token ContinueWithActionSetOrySessionToken show_verification_ui ContinueWithActionShowVerificationUI */
    @SerialName(value = "action") @Required val action: ContinueWith.Action
    @SerialName(value = "flow") @Required val flow: ContinueWithVerificationUiFlow
    /* Token is the token of the session */
    @SerialName(value = "ory_session_token") @Required val orySessionToken: kotlin.String
    /**
     * Action will always be `set_ory_session_token` set_ory_session_token ContinueWithActionSetOrySessionToken show_verification_ui ContinueWithActionShowVerificationUI
     *
     * Values: SET_ORY_SESSION_TOKEN,SHOW_VERIFICATION_UI
     */
    @Serializable
    enum class Action(val value: kotlin.String) {
        @SerialName(value = "set_ory_session_token") SET_ORY_SESSION_TOKEN("set_ory_session_token"),
        @SerialName(value = "show_verification_ui") SHOW_VERIFICATION_UI("show_verification_ui");
    }
}

