/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package sh.ory.model

import sh.ory.model.ContinueWithSettingsUiFlow

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Indicates, that the UI flow could be continued by showing a settings ui
 *
 * @param action Action will always be `show_settings_ui` show_settings_ui ContinueWithActionShowSettingsUIString
 * @param flow 
 */
@Serializable

data class ContinueWithSettingsUi (

    /* Action will always be `show_settings_ui` show_settings_ui ContinueWithActionShowSettingsUIString */
    @SerialName(value = "action") @Required val action: ContinueWithSettingsUi.Action,

    @SerialName(value = "flow") @Required val flow: ContinueWithSettingsUiFlow

) {

    /**
     * Action will always be `show_settings_ui` show_settings_ui ContinueWithActionShowSettingsUIString
     *
     * Values: SHOW_SETTINGS_UI
     */
    @Serializable
    enum class Action(val value: kotlin.String) {
        @SerialName(value = "show_settings_ui") SHOW_SETTINGS_UI("show_settings_ui");
    }
}

