/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package sh.ory.model


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param name The Token Name  A descriptive name for the token.  in: body
 */
@Serializable

data class CreateProjectApiKeyRequest (

    /* The Token Name  A descriptive name for the token.  in: body */
    @SerialName(value = "name") @Required val name: kotlin.String

)

