/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package sh.ory.model

import sh.ory.model.MemberInvite

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param allInvites A list of all invites for this resource
 * @param createdInvite 
 */
@Serializable

data class CreateInviteResponse (

    /* A list of all invites for this resource */
    @SerialName(value = "all_invites") @Required val allInvites: kotlin.Array<MemberInvite>,

    @SerialName(value = "created_invite") @Required val createdInvite: MemberInvite

)

