/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package sh.ory.model

import sh.ory.model.VerifiableCredentialProof

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param format 
 * @param proof 
 * @param types 
 */
@Serializable

data class CreateVerifiableCredentialRequestBody (

    @SerialName(value = "format") val format: kotlin.String? = null,

    @SerialName(value = "proof") val proof: VerifiableCredentialProof? = null,

    @SerialName(value = "types") val types: kotlin.Array<kotlin.String>? = null

)

