/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package sh.ory.model


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Create Workspace Invite Request Body
 *
 * @param inviteeEmail A email to invite
 */
@Serializable

data class CreateWorkspaceMemberInviteBody (

    /* A email to invite */
    @SerialName(value = "invitee_email") val inviteeEmail: kotlin.String? = null

)

