/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package sh.ory.model


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Create Project Request Body
 *
 * @param environment The environment of the project. prod Production stage Staging dev Development
 * @param name The name of the project to be created
 * @param workspaceId The workspace to create the project in.
 */
@Serializable

data class CreateProjectBody (

    /* The environment of the project. prod Production stage Staging dev Development */
    @SerialName(value = "environment") @Required val environment: CreateProjectBody.Environment,

    /* The name of the project to be created */
    @SerialName(value = "name") @Required val name: kotlin.String,

    /* The workspace to create the project in. */
    @SerialName(value = "workspace_id") val workspaceId: kotlin.String? = null

) {

    /**
     * The environment of the project. prod Production stage Staging dev Development
     *
     * Values: PROD,STAGE,DEV
     */
    @Serializable
    enum class Environment(val value: kotlin.String) {
        @SerialName(value = "prod") PROD("prod"),
        @SerialName(value = "stage") STAGE("stage"),
        @SerialName(value = "dev") DEV("dev");
    }
}

