/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package sh.ory.model


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Custom Hostname
 *
 * @param cookieDomain 
 * @param corsAllowedOrigins 
 * @param corsEnabled 
 * @param createdAt 
 * @param customUiBaseUrl 
 * @param hostname 
 * @param id 
 * @param sslStatus 
 * @param updatedAt 
 * @param verificationErrors 
 * @param verificationStatus 
 */
@Serializable

data class CustomDomain (

    @SerialName(value = "cookie_domain") val cookieDomain: kotlin.String? = null,

    @SerialName(value = "cors_allowed_origins") val corsAllowedOrigins: kotlin.Array<kotlin.String>? = null,

    @SerialName(value = "cors_enabled") val corsEnabled: kotlin.Boolean? = null,

    @SerialName(value = "created_at") val createdAt: kotlinx.datetime.Instant? = null,

    @SerialName(value = "custom_ui_base_url") val customUiBaseUrl: kotlin.String? = null,

    @SerialName(value = "hostname") val hostname: kotlin.String? = null,

    @SerialName(value = "id") val id: kotlin.String? = null,

    @SerialName(value = "ssl_status") val sslStatus: CustomDomain.SslStatus? = null,

    @SerialName(value = "updated_at") val updatedAt: kotlinx.datetime.Instant? = null,

    @SerialName(value = "verification_errors") val verificationErrors: kotlin.Array<kotlin.String>? = null,

    @SerialName(value = "verification_status") val verificationStatus: kotlin.String? = null

) {

    /**
     * 
     *
     * Values: INITIALIZING,PENDING_VALIDATION,DELETED,PENDING_ISSUANCE,PENDING_DEPLOYMENT,PENDING_DELETION,PENDING_EXPIRATION,EXPIRED,ACTIVE,INITIALIZING_TIMED_OUT,VALIDATION_TIMED_OUT,ISSUANCE_TIMED_OUT,DEPLOYMENT_TIMED_OUT,DELETION_TIMED_OUT,PENDING_CLEANUP,STAGING_DEPLOYMENT,STAGING_ACTIVE,DEACTIVATING,INACTIVE,BACKUP_ISSUED,HOLDING_DEPLOYMENT,EMPTY
     */
    @Serializable
    enum class SslStatus(val value: kotlin.String) {
        @SerialName(value = "initializing") INITIALIZING("initializing"),
        @SerialName(value = "pending_validation") PENDING_VALIDATION("pending_validation"),
        @SerialName(value = "deleted") DELETED("deleted"),
        @SerialName(value = "pending_issuance") PENDING_ISSUANCE("pending_issuance"),
        @SerialName(value = "pending_deployment") PENDING_DEPLOYMENT("pending_deployment"),
        @SerialName(value = "pending_deletion") PENDING_DELETION("pending_deletion"),
        @SerialName(value = "pending_expiration") PENDING_EXPIRATION("pending_expiration"),
        @SerialName(value = "expired") EXPIRED("expired"),
        @SerialName(value = "active") ACTIVE("active"),
        @SerialName(value = "initializing_timed_out") INITIALIZING_TIMED_OUT("initializing_timed_out"),
        @SerialName(value = "validation_timed_out") VALIDATION_TIMED_OUT("validation_timed_out"),
        @SerialName(value = "issuance_timed_out") ISSUANCE_TIMED_OUT("issuance_timed_out"),
        @SerialName(value = "deployment_timed_out") DEPLOYMENT_TIMED_OUT("deployment_timed_out"),
        @SerialName(value = "deletion_timed_out") DELETION_TIMED_OUT("deletion_timed_out"),
        @SerialName(value = "pending_cleanup") PENDING_CLEANUP("pending_cleanup"),
        @SerialName(value = "staging_deployment") STAGING_DEPLOYMENT("staging_deployment"),
        @SerialName(value = "staging_active") STAGING_ACTIVE("staging_active"),
        @SerialName(value = "deactivating") DEACTIVATING("deactivating"),
        @SerialName(value = "inactive") INACTIVE("inactive"),
        @SerialName(value = "backup_issued") BACKUP_ISSUED("backup_issued"),
        @SerialName(value = "holding_deployment") HOLDING_DEPLOYMENT("holding_deployment"),
        @SerialName(value = "") EMPTY("");
    }
}

