/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package sh.ory.model

import sh.ory.model.EmailTemplateDataBody

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Contains the data of the email template, including the subject and body in HTML and plaintext variants
 *
 * @param body 
 * @param subject 
 */
@Serializable

data class EmailTemplateData (

    @SerialName(value = "body") @Required val body: EmailTemplateDataBody,

    @SerialName(value = "subject") @Required val subject: kotlin.String

)

