/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package sh.ory.model

import sh.ory.model.Relationship

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param type The type of the node. union TreeNodeUnion exclusion TreeNodeExclusion intersection TreeNodeIntersection leaf TreeNodeLeaf tuple_to_subject_set TreeNodeTupleToSubjectSet computed_subject_set TreeNodeComputedSubjectSet not TreeNodeNot unspecified TreeNodeUnspecified
 * @param children The children of the node, possibly none.
 * @param tuple 
 */
@Serializable

data class ExpandedPermissionTree (

    /* The type of the node. union TreeNodeUnion exclusion TreeNodeExclusion intersection TreeNodeIntersection leaf TreeNodeLeaf tuple_to_subject_set TreeNodeTupleToSubjectSet computed_subject_set TreeNodeComputedSubjectSet not TreeNodeNot unspecified TreeNodeUnspecified */
    @SerialName(value = "type") @Required val type: ExpandedPermissionTree.Type,

    /* The children of the node, possibly none. */
    @SerialName(value = "children") val children: kotlin.Array<ExpandedPermissionTree>? = null,

    @SerialName(value = "tuple") val tuple: Relationship? = null

) {

    /**
     * The type of the node. union TreeNodeUnion exclusion TreeNodeExclusion intersection TreeNodeIntersection leaf TreeNodeLeaf tuple_to_subject_set TreeNodeTupleToSubjectSet computed_subject_set TreeNodeComputedSubjectSet not TreeNodeNot unspecified TreeNodeUnspecified
     *
     * Values: UNION,EXCLUSION,INTERSECTION,LEAF,TUPLE_TO_SUBJECT_SET,COMPUTED_SUBJECT_SET,NOT,UNSPECIFIED
     */
    @Serializable
    enum class Type(val value: kotlin.String) {
        @SerialName(value = "union") UNION("union"),
        @SerialName(value = "exclusion") EXCLUSION("exclusion"),
        @SerialName(value = "intersection") INTERSECTION("intersection"),
        @SerialName(value = "leaf") LEAF("leaf"),
        @SerialName(value = "tuple_to_subject_set") TUPLE_TO_SUBJECT_SET("tuple_to_subject_set"),
        @SerialName(value = "computed_subject_set") COMPUTED_SUBJECT_SET("computed_subject_set"),
        @SerialName(value = "not") NOT("not"),
        @SerialName(value = "unspecified") UNSPECIFIED("unspecified");
    }
}

