/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package sh.ory.model


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param additionalPrice AdditionalPrice is the price per-unit in cent exceeding IncludedUsage. A price of 0 means that no other items can be consumed.
 * @param includedUsage IncludedUsage is the number of included items.
 */
@Serializable

data class GenericUsage (

    /* AdditionalPrice is the price per-unit in cent exceeding IncludedUsage. A price of 0 means that no other items can be consumed. */
    @SerialName(value = "additional_price") @Required val additionalPrice: kotlin.Long,

    /* IncludedUsage is the number of included items. */
    @SerialName(value = "included_usage") @Required val includedUsage: kotlin.Long

)

