/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package sh.ory.model


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * CredentialsCode represents a one time login/registration code
 *
 * @param addressType The type of the address for this code
 * @param usedAt 
 */
@Serializable

data class IdentityCredentialsCode (

    /* The type of the address for this code */
    @SerialName(value = "address_type") val addressType: kotlin.String? = null,

    @SerialName(value = "used_at") val usedAt: @Contextual kotlin.time.Instant? = null

)

