/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package sh.ory.model


import kotlinx.serialization.*

/**
 * and so on.
 *
 * Values: PASSWORD,TOTP,OIDC,WEBAUTHN,LOOKUP_SECRET
 */
@Serializable
enum class IdentityCredentialsType(val value: kotlin.String) {

    @SerialName(value = "password")
    PASSWORD("password"),

    @SerialName(value = "totp")
    TOTP("totp"),

    @SerialName(value = "oidc")
    OIDC("oidc"),

    @SerialName(value = "webauthn")
    WEBAUTHN("webauthn"),

    @SerialName(value = "lookup_secret")
    LOOKUP_SECRET("lookup_secret");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is IdentityCredentialsType) "$data" else null

        /**
         * Returns a valid [IdentityCredentialsType] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): IdentityCredentialsType? = data?.let {
          val normalizedData = "$it".lowercase()
          values().firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

