/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package sh.ory.model


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Is Owner For Project By Slug Request Body
 *
 * @param namespace Namespace is the namespace of the subject.
 * @param projectSlug ProjectSlug is the project's slug.
 * @param subject Subject is the subject acting (user or API key).
 * @param projectScope ProjectScope is the project_id resolved from the API Token.
 */
@Serializable

data class InternalIsOwnerForProjectBySlugBody (

    /* Namespace is the namespace of the subject. */
    @SerialName(value = "namespace") @Required val namespace: InternalIsOwnerForProjectBySlugBody.Namespace,

    /* ProjectSlug is the project's slug. */
    @SerialName(value = "project_slug") @Required val projectSlug: kotlin.String,

    /* Subject is the subject acting (user or API key). */
    @SerialName(value = "subject") @Required val subject: kotlin.String,

    /* ProjectScope is the project_id resolved from the API Token. */
    @SerialName(value = "project_scope") val projectScope: kotlin.String? = null

) {

    /**
     * Namespace is the namespace of the subject.
     *
     * Values: USER,_API_KEY
     */
    @Serializable
    enum class Namespace(val value: kotlin.String) {
        @SerialName(value = "User") USER("User"),
        @SerialName(value = " ApiKey") _API_KEY(" ApiKey");
    }
}

