/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package sh.ory.model

import sh.ory.model.WorkspaceMeta

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param hasNextPage 
 * @param nextPageToken 
 * @param workspaces 
 */
@Serializable

data class ListMyWorkspacesResponse (

    @SerialName(value = "has_next_page") @Required val hasNextPage: kotlin.Boolean,

    @SerialName(value = "next_page_token") @Required val nextPageToken: kotlin.String,

    @SerialName(value = "workspaces") @Required val workspaces: kotlin.Array<WorkspaceMeta>

)

