/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package sh.ory.model

import sh.ory.model.ProjectMetadata

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param hasNextPage 
 * @param nextPage 
 * @param projects 
 */
@Serializable

data class ListWorkspaceProjectsResponse (

    @SerialName(value = "has_next_page") @Required val hasNextPage: kotlin.Boolean,

    @SerialName(value = "next_page") @Required val nextPage: kotlin.String,

    @SerialName(value = "projects") @Required val projects: kotlin.Array<ProjectMetadata>

)

