/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package sh.ory.model


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param createdAt The Project's Revision Creation Date
 * @param id The invite's ID.
 * @param inviteeEmail The invitee's email
 * @param ownerEmail The invite owner's email Usually the project's owner email
 * @param ownerId The invite owner's ID Usually the project's owner
 * @param status The invite's status Keeps track of the invites status such as pending, accepted, declined, expired pending PENDING accepted ACCEPTED declined DECLINED expired EXPIRED cancelled CANCELLED removed REMOVED
 * @param updatedAt Last Time Project's Revision was Updated
 * @param inviteeId 
 * @param projectId 
 * @param workspaceId 
 */
@Serializable

data class MemberInvite (

    /* The Project's Revision Creation Date */
    @SerialName(value = "created_at") @Required val createdAt: @Contextual kotlin.time.Instant,

    /* The invite's ID. */
    @SerialName(value = "id") @Required val id: kotlin.String,

    /* The invitee's email */
    @SerialName(value = "invitee_email") @Required val inviteeEmail: kotlin.String,

    /* The invite owner's email Usually the project's owner email */
    @SerialName(value = "owner_email") @Required val ownerEmail: kotlin.String,

    /* The invite owner's ID Usually the project's owner */
    @SerialName(value = "owner_id") @Required val ownerId: kotlin.String,

    /* The invite's status Keeps track of the invites status such as pending, accepted, declined, expired pending PENDING accepted ACCEPTED declined DECLINED expired EXPIRED cancelled CANCELLED removed REMOVED */
    @SerialName(value = "status") @Required val status: MemberInvite.Status,

    /* Last Time Project's Revision was Updated */
    @SerialName(value = "updated_at") @Required val updatedAt: @Contextual kotlin.time.Instant,

    @SerialName(value = "invitee_id") val inviteeId: kotlin.String? = null,

    @SerialName(value = "project_id") val projectId: kotlin.String? = null,

    @SerialName(value = "workspace_id") val workspaceId: kotlin.String? = null

) {

    /**
     * The invite's status Keeps track of the invites status such as pending, accepted, declined, expired pending PENDING accepted ACCEPTED declined DECLINED expired EXPIRED cancelled CANCELLED removed REMOVED
     *
     * Values: PENDING,ACCEPTED,DECLINED,EXPIRED,CANCELLED,REMOVED
     */
    @Serializable
    enum class Status(val value: kotlin.String) {
        @SerialName(value = "pending") PENDING("pending"),
        @SerialName(value = "accepted") ACCEPTED("accepted"),
        @SerialName(value = "declined") DECLINED("declined"),
        @SerialName(value = "expired") EXPIRED("expired"),
        @SerialName(value = "cancelled") CANCELLED("cancelled"),
        @SerialName(value = "removed") REMOVED("removed");
    }
}

