/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package sh.ory.model

import sh.ory.model.CourierMessageStatus
import sh.ory.model.CourierMessageType
import sh.ory.model.MessageDispatch

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param body 
 * @param createdAt CreatedAt is a helper struct field for gobuffalo.pop.
 * @param id 
 * @param recipient 
 * @param sendCount 
 * @param status 
 * @param subject 
 * @param templateType  recovery_invalid TypeRecoveryInvalid recovery_valid TypeRecoveryValid recovery_code_invalid TypeRecoveryCodeInvalid recovery_code_valid TypeRecoveryCodeValid verification_invalid TypeVerificationInvalid verification_valid TypeVerificationValid verification_code_invalid TypeVerificationCodeInvalid verification_code_valid TypeVerificationCodeValid otp TypeOTP stub TypeTestStub
 * @param type 
 * @param updatedAt UpdatedAt is a helper struct field for gobuffalo.pop.
 * @param dispatches Dispatches store information about the attempts of delivering a message May contain an error if any happened, or just the `success` state.
 */
@Serializable

data class Message (

    @SerialName(value = "body") @Required val body: kotlin.String,

    /* CreatedAt is a helper struct field for gobuffalo.pop. */
    @SerialName(value = "created_at") @Required val createdAt: kotlinx.datetime.Instant,

    @SerialName(value = "id") @Required val id: kotlin.String,

    @SerialName(value = "recipient") @Required val recipient: kotlin.String,

    @SerialName(value = "send_count") @Required val sendCount: kotlin.Long,

    @SerialName(value = "status") @Required val status: CourierMessageStatus,

    @SerialName(value = "subject") @Required val subject: kotlin.String,

    /*  recovery_invalid TypeRecoveryInvalid recovery_valid TypeRecoveryValid recovery_code_invalid TypeRecoveryCodeInvalid recovery_code_valid TypeRecoveryCodeValid verification_invalid TypeVerificationInvalid verification_valid TypeVerificationValid verification_code_invalid TypeVerificationCodeInvalid verification_code_valid TypeVerificationCodeValid otp TypeOTP stub TypeTestStub */
    @SerialName(value = "template_type") @Required val templateType: Message.TemplateType,

    @SerialName(value = "type") @Required val type: CourierMessageType,

    /* UpdatedAt is a helper struct field for gobuffalo.pop. */
    @SerialName(value = "updated_at") @Required val updatedAt: kotlinx.datetime.Instant,

    /* Dispatches store information about the attempts of delivering a message May contain an error if any happened, or just the `success` state. */
    @SerialName(value = "dispatches") val dispatches: kotlin.Array<MessageDispatch>? = null

) {

    /**
     *  recovery_invalid TypeRecoveryInvalid recovery_valid TypeRecoveryValid recovery_code_invalid TypeRecoveryCodeInvalid recovery_code_valid TypeRecoveryCodeValid verification_invalid TypeVerificationInvalid verification_valid TypeVerificationValid verification_code_invalid TypeVerificationCodeInvalid verification_code_valid TypeVerificationCodeValid otp TypeOTP stub TypeTestStub
     *
     * Values: RECOVERY_INVALID,RECOVERY_VALID,RECOVERY_CODE_INVALID,RECOVERY_CODE_VALID,VERIFICATION_INVALID,VERIFICATION_VALID,VERIFICATION_CODE_INVALID,VERIFICATION_CODE_VALID,OTP,STUB
     */
    @Serializable
    enum class TemplateType(val value: kotlin.String) {
        @SerialName(value = "recovery_invalid") RECOVERY_INVALID("recovery_invalid"),
        @SerialName(value = "recovery_valid") RECOVERY_VALID("recovery_valid"),
        @SerialName(value = "recovery_code_invalid") RECOVERY_CODE_INVALID("recovery_code_invalid"),
        @SerialName(value = "recovery_code_valid") RECOVERY_CODE_VALID("recovery_code_valid"),
        @SerialName(value = "verification_invalid") VERIFICATION_INVALID("verification_invalid"),
        @SerialName(value = "verification_valid") VERIFICATION_VALID("verification_valid"),
        @SerialName(value = "verification_code_invalid") VERIFICATION_CODE_INVALID("verification_code_invalid"),
        @SerialName(value = "verification_code_valid") VERIFICATION_CODE_VALID("verification_code_valid"),
        @SerialName(value = "otp") OTP("otp"),
        @SerialName(value = "stub") STUB("stub");
    }
}

