/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package sh.ory.model

import sh.ory.model.Workspace

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param createdAt The Project's Creation Date
 * @param environment The environment of the project. prod Production stage Staging dev Development
 * @param hosts 
 * @param id The project's ID.
 * @param name The project's name if set
 * @param state The state of the project. running Running halted Halted deleted Deleted
 * @param updatedAt Last Time Project was Updated
 * @param slug The project's slug
 * @param subscriptionId 
 * @param subscriptionPlan 
 * @param workspace 
 * @param workspaceId 
 */
@Serializable

data class ProjectMetadata (

    /* The Project's Creation Date */
    @SerialName(value = "created_at") @Required val createdAt: kotlinx.datetime.Instant,

    /* The environment of the project. prod Production stage Staging dev Development */
    @SerialName(value = "environment") @Required val environment: ProjectMetadata.Environment,

    @SerialName(value = "hosts") @Required val hosts: kotlin.Array<kotlin.String>,

    /* The project's ID. */
    @SerialName(value = "id") @Required val id: kotlin.String,

    /* The project's name if set */
    @SerialName(value = "name") @Required val name: kotlin.String,

    /* The state of the project. running Running halted Halted deleted Deleted */
    @SerialName(value = "state") @Required val state: ProjectMetadata.State,

    /* Last Time Project was Updated */
    @SerialName(value = "updated_at") @Required val updatedAt: kotlinx.datetime.Instant,

    /* The project's slug */
    @SerialName(value = "slug") val slug: kotlin.String? = null,

    @SerialName(value = "subscription_id") val subscriptionId: kotlin.String? = null,

    @SerialName(value = "subscription_plan") val subscriptionPlan: kotlin.String? = null,

    @SerialName(value = "workspace") val workspace: Workspace? = null,

    @SerialName(value = "workspace_id") val workspaceId: kotlin.String? = null

) {

    /**
     * The environment of the project. prod Production stage Staging dev Development
     *
     * Values: PROD,STAGE,DEV
     */
    @Serializable
    enum class Environment(val value: kotlin.String) {
        @SerialName(value = "prod") PROD("prod"),
        @SerialName(value = "stage") STAGE("stage"),
        @SerialName(value = "dev") DEV("dev");
    }
    /**
     * The state of the project. running Running halted Halted deleted Deleted
     *
     * Values: RUNNING,HALTED,DELETED
     */
    @Serializable
    enum class State(val value: kotlin.String) {
        @SerialName(value = "running") RUNNING("running"),
        @SerialName(value = "halted") HALTED("halted"),
        @SerialName(value = "deleted") DELETED("deleted");
    }
}

