/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package sh.ory.model

import sh.ory.model.ProjectCors
import sh.ory.model.ProjectServices

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param id The project's ID.
 * @param name The name of the project.
 * @param revisionId The configuration revision ID.
 * @param services 
 * @param slug The project's slug
 * @param state The state of the project. running Running halted Halted deleted Deleted
 * @param corsAdmin 
 * @param corsPublic 
 * @param workspaceId 
 */
@Serializable

data class Project (

    /* The project's ID. */
    @SerialName(value = "id") @Required val id: kotlin.String,

    /* The name of the project. */
    @SerialName(value = "name") @Required val name: kotlin.String,

    /* The configuration revision ID. */
    @SerialName(value = "revision_id") @Required val revisionId: kotlin.String,

    @SerialName(value = "services") @Required val services: ProjectServices,

    /* The project's slug */
    @SerialName(value = "slug") @Required val slug: kotlin.String,

    /* The state of the project. running Running halted Halted deleted Deleted */
    @SerialName(value = "state") @Required val state: Project.State,

    @SerialName(value = "cors_admin") val corsAdmin: ProjectCors? = null,

    @SerialName(value = "cors_public") val corsPublic: ProjectCors? = null,

    @SerialName(value = "workspace_id") val workspaceId: kotlin.String? = null

) {

    /**
     * The state of the project. running Running halted Halted deleted Deleted
     *
     * Values: RUNNING,HALTED,DELETED
     */
    @Serializable
    enum class State(val value: kotlin.String) {
        @SerialName(value = "running") RUNNING("running"),
        @SerialName(value = "halted") HALTED("halted"),
        @SerialName(value = "deleted") DELETED("deleted");
    }
}

