/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package sh.ory.model

import sh.ory.model.ProjectServiceIdentity
import sh.ory.model.ProjectServiceOAuth2
import sh.ory.model.ProjectServicePermission

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param identity 
 * @param oauth2 
 * @param permission 
 */
@Serializable

data class ProjectServices (

    @SerialName(value = "identity") val identity: ProjectServiceIdentity? = null,

    @SerialName(value = "oauth2") val oauth2: ProjectServiceOAuth2? = null,

    @SerialName(value = "permission") val permission: ProjectServicePermission? = null

)

