/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package sh.ory.model


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param additionalPrice The additional price per unit in cents.
 * @param canUseMore 
 * @param feature  region_eu RegionEU region_us RegionUS region_apac RegionAPAC region_global RegionGlobal production_projects ProductionProjects staging_projects StagingProjects development_projects DevelopmentProjects daily_active_users DailyActiveUsers custom_domains CustomDomains event_streams EventStreams sla SLA collaborator_seats CollaboratorSeats edge_cache EdgeCache branding_themes BrandingThemes zendesk_support ZendeskSupport project_metrics ProjectMetrics project_metrics_time_window ProjectMetricsTimeWindow project_metrics_events_history ProjectMetricsEventsHistory organizations Organizations rop_grant ResourceOwnerPasswordGrant concierge_onboarding ConciergeOnboarding credit Credit rate_limit_tier RateLimitTier session_rate_limit_tier RateLimitTierSessions identities_list_rate_limit_tier RateLimitTierIdentitiesList permission_checks_rate_limit_tier RateLimitTierPermissionChecks oauth2_introspect_rate_limit_tier RateLimitTierOAuth2Introspect
 * @param featureAvailable 
 * @param included 
 * @param used 
 */
@Serializable

data class QuotaUsage (

    /* The additional price per unit in cents. */
    @SerialName(value = "additional_price") @Required val additionalPrice: kotlin.Long,

    @SerialName(value = "can_use_more") @Required val canUseMore: kotlin.Boolean,

    /*  region_eu RegionEU region_us RegionUS region_apac RegionAPAC region_global RegionGlobal production_projects ProductionProjects staging_projects StagingProjects development_projects DevelopmentProjects daily_active_users DailyActiveUsers custom_domains CustomDomains event_streams EventStreams sla SLA collaborator_seats CollaboratorSeats edge_cache EdgeCache branding_themes BrandingThemes zendesk_support ZendeskSupport project_metrics ProjectMetrics project_metrics_time_window ProjectMetricsTimeWindow project_metrics_events_history ProjectMetricsEventsHistory organizations Organizations rop_grant ResourceOwnerPasswordGrant concierge_onboarding ConciergeOnboarding credit Credit rate_limit_tier RateLimitTier session_rate_limit_tier RateLimitTierSessions identities_list_rate_limit_tier RateLimitTierIdentitiesList permission_checks_rate_limit_tier RateLimitTierPermissionChecks oauth2_introspect_rate_limit_tier RateLimitTierOAuth2Introspect */
    @SerialName(value = "feature") @Required val feature: QuotaUsage.Feature,

    @SerialName(value = "feature_available") @Required val featureAvailable: kotlin.Boolean,

    @SerialName(value = "included") @Required val included: kotlin.Long,

    @SerialName(value = "used") @Required val used: kotlin.Long

) {

    /**
     *  region_eu RegionEU region_us RegionUS region_apac RegionAPAC region_global RegionGlobal production_projects ProductionProjects staging_projects StagingProjects development_projects DevelopmentProjects daily_active_users DailyActiveUsers custom_domains CustomDomains event_streams EventStreams sla SLA collaborator_seats CollaboratorSeats edge_cache EdgeCache branding_themes BrandingThemes zendesk_support ZendeskSupport project_metrics ProjectMetrics project_metrics_time_window ProjectMetricsTimeWindow project_metrics_events_history ProjectMetricsEventsHistory organizations Organizations rop_grant ResourceOwnerPasswordGrant concierge_onboarding ConciergeOnboarding credit Credit rate_limit_tier RateLimitTier session_rate_limit_tier RateLimitTierSessions identities_list_rate_limit_tier RateLimitTierIdentitiesList permission_checks_rate_limit_tier RateLimitTierPermissionChecks oauth2_introspect_rate_limit_tier RateLimitTierOAuth2Introspect
     *
     * Values: REGION_EU,REGION_US,REGION_APAC,REGION_GLOBAL,PRODUCTION_PROJECTS,STAGING_PROJECTS,DEVELOPMENT_PROJECTS,DAILY_ACTIVE_USERS,CUSTOM_DOMAINS,EVENT_STREAMS,SLA,COLLABORATOR_SEATS,EDGE_CACHE,BRANDING_THEMES,ZENDESK_SUPPORT,PROJECT_METRICS,PROJECT_METRICS_TIME_WINDOW,PROJECT_METRICS_EVENTS_HISTORY,ORGANIZATIONS,ROP_GRANT,CONCIERGE_ONBOARDING,CREDIT,RATE_LIMIT_TIER,SESSION_RATE_LIMIT_TIER,IDENTITIES_LIST_RATE_LIMIT_TIER,PERMISSION_CHECKS_RATE_LIMIT_TIER,OAUTH2_INTROSPECT_RATE_LIMIT_TIER
     */
    @Serializable
    enum class Feature(val value: kotlin.String) {
        @SerialName(value = "region_eu") REGION_EU("region_eu"),
        @SerialName(value = "region_us") REGION_US("region_us"),
        @SerialName(value = "region_apac") REGION_APAC("region_apac"),
        @SerialName(value = "region_global") REGION_GLOBAL("region_global"),
        @SerialName(value = "production_projects") PRODUCTION_PROJECTS("production_projects"),
        @SerialName(value = "staging_projects") STAGING_PROJECTS("staging_projects"),
        @SerialName(value = "development_projects") DEVELOPMENT_PROJECTS("development_projects"),
        @SerialName(value = "daily_active_users") DAILY_ACTIVE_USERS("daily_active_users"),
        @SerialName(value = "custom_domains") CUSTOM_DOMAINS("custom_domains"),
        @SerialName(value = "event_streams") EVENT_STREAMS("event_streams"),
        @SerialName(value = "sla") SLA("sla"),
        @SerialName(value = "collaborator_seats") COLLABORATOR_SEATS("collaborator_seats"),
        @SerialName(value = "edge_cache") EDGE_CACHE("edge_cache"),
        @SerialName(value = "branding_themes") BRANDING_THEMES("branding_themes"),
        @SerialName(value = "zendesk_support") ZENDESK_SUPPORT("zendesk_support"),
        @SerialName(value = "project_metrics") PROJECT_METRICS("project_metrics"),
        @SerialName(value = "project_metrics_time_window") PROJECT_METRICS_TIME_WINDOW("project_metrics_time_window"),
        @SerialName(value = "project_metrics_events_history") PROJECT_METRICS_EVENTS_HISTORY("project_metrics_events_history"),
        @SerialName(value = "organizations") ORGANIZATIONS("organizations"),
        @SerialName(value = "rop_grant") ROP_GRANT("rop_grant"),
        @SerialName(value = "concierge_onboarding") CONCIERGE_ONBOARDING("concierge_onboarding"),
        @SerialName(value = "credit") CREDIT("credit"),
        @SerialName(value = "rate_limit_tier") RATE_LIMIT_TIER("rate_limit_tier"),
        @SerialName(value = "session_rate_limit_tier") SESSION_RATE_LIMIT_TIER("session_rate_limit_tier"),
        @SerialName(value = "identities_list_rate_limit_tier") IDENTITIES_LIST_RATE_LIMIT_TIER("identities_list_rate_limit_tier"),
        @SerialName(value = "permission_checks_rate_limit_tier") PERMISSION_CHECKS_RATE_LIMIT_TIER("permission_checks_rate_limit_tier"),
        @SerialName(value = "oauth2_introspect_rate_limit_tier") OAUTH2_INTROSPECT_RATE_LIMIT_TIER("oauth2_introspect_rate_limit_tier");
    }
}

