/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package sh.ory.model

import sh.ory.model.Relationship

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Payload for patching a relationship
 *
 * @param action 
 * @param relationTuple 
 */
@Serializable

data class RelationshipPatch (

    @SerialName(value = "action") val action: RelationshipPatch.Action? = null,

    @SerialName(value = "relation_tuple") val relationTuple: Relationship? = null

) {

    /**
     * 
     *
     * Values: INSERT,DELETE
     */
    @Serializable
    enum class Action(val value: kotlin.String) {
        @SerialName(value = "insert") INSERT("insert"),
        @SerialName(value = "delete") DELETE("delete");
    }
}

