/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package sh.ory.model

import sh.ory.model.AuthenticatorAssuranceLevel
import sh.ory.model.Identity
import sh.ory.model.SessionAuthenticationMethod
import sh.ory.model.SessionDevice

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * A Session
 *
 * @param id Session ID
 * @param identity 
 * @param active Active state. If false the session is no longer active.
 * @param authenticatedAt The Session Authentication Timestamp  When this session was authenticated at. If multi-factor authentication was used this is the time when the last factor was authenticated (e.g. the TOTP code challenge was completed).
 * @param authenticationMethods A list of authenticators which were used to authenticate the session.
 * @param authenticatorAssuranceLevel 
 * @param devices Devices has history of all endpoints where the session was used
 * @param expiresAt The Session Expiry  When this session expires at.
 * @param issuedAt The Session Issuance Timestamp  When this session was issued at. Usually equal or close to `authenticated_at`.
 */
@Serializable

data class Session (

    /* Session ID */
    @SerialName(value = "id") @Required val id: kotlin.String,

    @SerialName(value = "identity") @Required val identity: Identity,

    /* Active state. If false the session is no longer active. */
    @SerialName(value = "active") val active: kotlin.Boolean? = null,

    /* The Session Authentication Timestamp  When this session was authenticated at. If multi-factor authentication was used this is the time when the last factor was authenticated (e.g. the TOTP code challenge was completed). */
    @SerialName(value = "authenticated_at") val authenticatedAt: kotlinx.datetime.Instant? = null,

    /* A list of authenticators which were used to authenticate the session. */
    @SerialName(value = "authentication_methods") val authenticationMethods: kotlin.Array<SessionAuthenticationMethod>? = null,

    @SerialName(value = "authenticator_assurance_level") val authenticatorAssuranceLevel: AuthenticatorAssuranceLevel? = null,

    /* Devices has history of all endpoints where the session was used */
    @SerialName(value = "devices") val devices: kotlin.Array<SessionDevice>? = null,

    /* The Session Expiry  When this session expires at. */
    @SerialName(value = "expires_at") val expiresAt: kotlinx.datetime.Instant? = null,

    /* The Session Issuance Timestamp  When this session was issued at. Usually equal or close to `authenticated_at`. */
    @SerialName(value = "issued_at") val issuedAt: kotlinx.datetime.Instant? = null

)

