/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package sh.ory.model

import kotlinx.serialization.*
import kotlinx.serialization.json.JsonObject

/**
 * InputAttributes represents the attributes of an input node
 *
 * @param disabled Sets the input's disabled field to true or false.
 * @param name The input's element name.
 * @param nodeType NodeType represents this node's types. It is a mirror of `node.type` and is primarily used to allow compatibility with OpenAPI 3.0.  In this struct it technically always is \"input\". text Text input Input img Image a Anchor script Script
 * @param type The input's element type. text InputAttributeTypeText password InputAttributeTypePassword number InputAttributeTypeNumber checkbox InputAttributeTypeCheckbox hidden InputAttributeTypeHidden email InputAttributeTypeEmail tel InputAttributeTypeTel submit InputAttributeTypeSubmit button InputAttributeTypeButton datetime-local InputAttributeTypeDateTimeLocal date InputAttributeTypeDate url InputAttributeTypeURI
 * @param autocomplete The autocomplete attribute for the input. email InputAttributeAutocompleteEmail tel InputAttributeAutocompleteTel url InputAttributeAutocompleteUrl current-password InputAttributeAutocompleteCurrentPassword new-password InputAttributeAutocompleteNewPassword one-time-code InputAttributeAutocompleteOneTimeCode
 * @param label 
 * @param onclick OnClick may contain javascript which should be executed on click. This is primarily used for WebAuthn.
 * @param onload OnLoad may contain javascript which should be executed on load. This is primarily used for WebAuthn.
 * @param pattern The input's pattern.
 * @param required Mark this input field as required.
 * @param `value` The input's value.
 */
@Serializable
sealed class UiNodeInputAttributes (

    /* Sets the input's disabled field to true or false. */
    @SerialName(value = "disabled") @Required val disabled: kotlin.Boolean,

    /* The input's element name. */
    @SerialName(value = "name") @Required val name: kotlin.String,

    /* NodeType represents this node's types. It is a mirror of `node.type` and is primarily used to allow compatibility with OpenAPI 3.0.  In this struct it technically always is \"input\". text Text input Input img Image a Anchor script Script */
    @SerialName(value = "node_type") @Required val nodeType: kotlin.String, // UiNodeInputAttributes.NodeType

    /* The input's element type. text InputAttributeTypeText password InputAttributeTypePassword number InputAttributeTypeNumber checkbox InputAttributeTypeCheckbox hidden InputAttributeTypeHidden email InputAttributeTypeEmail tel InputAttributeTypeTel submit InputAttributeTypeSubmit button InputAttributeTypeButton datetime-local InputAttributeTypeDateTimeLocal date InputAttributeTypeDate url InputAttributeTypeURI */
    //@SerialName(value = "type") @Required val type: kotlin.String, // UiNodeInputAttributes.Type

    /* The autocomplete attribute for the input. email InputAttributeAutocompleteEmail tel InputAttributeAutocompleteTel url InputAttributeAutocompleteUrl current-password InputAttributeAutocompleteCurrentPassword new-password InputAttributeAutocompleteNewPassword one-time-code InputAttributeAutocompleteOneTimeCode */
    @SerialName(value = "autocomplete") val autocomplete: UiNodeInputAttributes.Autocomplete? = null,

    @SerialName(value = "label") val label: UiText? = null,

    /* OnClick may contain javascript which should be executed on click. This is primarily used for WebAuthn. */
    @SerialName(value = "onclick") val onclick: kotlin.String? = null,

    /* OnLoad may contain javascript which should be executed on load. This is primarily used for WebAuthn. */
    @SerialName(value = "onload") val onload: kotlin.String? = null,

    /* The input's pattern. */
    @SerialName(value = "pattern") val pattern: kotlin.String? = null,

    /* Mark this input field as required. */
    @SerialName(value = "required") val required: kotlin.Boolean? = null,

    /* The input's value. */
    @SerialName(value = "value") val `value`: JsonObject? = null

) {

    /**
     * NodeType represents this node's types. It is a mirror of `node.type` and is primarily used to allow compatibility with OpenAPI 3.0.  In this struct it technically always is \"input\". text Text input Input img Image a Anchor script Script
     *
     * Values: TEXT,INPUT,IMG,A,SCRIPT
     */
/*
    @Serializable
    enum class NodeType(val value: kotlin.String) {
        @SerialName(value = "text") TEXT("text"),
        @SerialName(value = "input") INPUT("input"),
        @SerialName(value = "img") IMG("img"),
        @SerialName(value = "a") A("a"),
        @SerialName(value = "script") SCRIPT("script");
    }
*/
    /**
     * The input's element type. text InputAttributeTypeText password InputAttributeTypePassword number InputAttributeTypeNumber checkbox InputAttributeTypeCheckbox hidden InputAttributeTypeHidden email InputAttributeTypeEmail tel InputAttributeTypeTel submit InputAttributeTypeSubmit button InputAttributeTypeButton datetime-local InputAttributeTypeDateTimeLocal date InputAttributeTypeDate url InputAttributeTypeURI
     *
     * Values: TEXT,PASSWORD,NUMBER,CHECKBOX,HIDDEN,EMAIL,TEL,SUBMIT,BUTTON,DATETIME_MINUS_LOCAL,DATE,URL
     */
/*
    @Serializable
    enum class Type(val value: kotlin.String) {
        @SerialName(value = "text") TEXT("text"),
        @SerialName(value = "password") PASSWORD("password"),
        @SerialName(value = "number") NUMBER("number"),
        @SerialName(value = "checkbox") CHECKBOX("checkbox"),
        @SerialName(value = "hidden") HIDDEN("hidden"),
        @SerialName(value = "email") EMAIL("email"),
        @SerialName(value = "tel") TEL("tel"),
        @SerialName(value = "submit") SUBMIT("submit"),
        @SerialName(value = "button") BUTTON("button"),
        @SerialName(value = "datetime-local") DATETIME_MINUS_LOCAL("datetime-local"),
        @SerialName(value = "date") DATE("date"),
        @SerialName(value = "url") URL("url");
    }
*/
    /**
     * The autocomplete attribute for the input. email InputAttributeAutocompleteEmail tel InputAttributeAutocompleteTel url InputAttributeAutocompleteUrl current-password InputAttributeAutocompleteCurrentPassword new-password InputAttributeAutocompleteNewPassword one-time-code InputAttributeAutocompleteOneTimeCode
     *
     * Values: EMAIL,TEL,URL,CURRENT_MINUS_PASSWORD,NEW_MINUS_PASSWORD,ONE_MINUS_TIME_MINUS_CODE
     */
    @Serializable
    enum class Autocomplete(val value: kotlin.String) {
        @SerialName(value = "email") EMAIL("email"),
        @SerialName(value = "tel") TEL("tel"),
        @SerialName(value = "url") URL("url"),
        @SerialName(value = "current-password") CURRENT_MINUS_PASSWORD("current-password"),
        @SerialName(value = "new-password") NEW_MINUS_PASSWORD("new-password"),
        @SerialName(value = "one-time-code") ONE_MINUS_TIME_MINUS_CODE("one-time-code");
    }
}

