/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package sh.ory.model

import sh.ory.model.UiNodeAnchorAttributes
import sh.ory.model.UiNodeImageAttributes
import sh.ory.model.UiNodeInputAttributes
import sh.ory.model.UiNodeScriptAttributes
import sh.ory.model.UiNodeTextAttributes
import sh.ory.model.UiText

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param disabled Sets the input's disabled field to true or false.
 * @param name The input's element name.
 * @param nodeType NodeType represents this node's types. It is a mirror of `node.type` and is primarily used to allow compatibility with OpenAPI 3.0. In this struct it technically always is \"script\".
 * @param type The script MIME type
 * @param id A unique identifier
 * @param text 
 * @param height Height of the image
 * @param src The script source
 * @param width Width of the image
 * @param href The link's href (destination) URL.  format: uri
 * @param title 
 * @param async The script async type
 * @param crossorigin The script cross origin policy
 * @param integrity The script's integrity hash
 * @param nonce Nonce for CSP  A nonce you may want to use to improve your Content Security Policy. You do not have to use this value but if you want to improve your CSP policies you may use it. You can also choose to use your own nonce value!
 * @param referrerpolicy The script referrer policy
 * @param autocomplete The autocomplete attribute for the input. email InputAttributeAutocompleteEmail tel InputAttributeAutocompleteTel url InputAttributeAutocompleteUrl current-password InputAttributeAutocompleteCurrentPassword new-password InputAttributeAutocompleteNewPassword one-time-code InputAttributeAutocompleteOneTimeCode
 * @param label 
 * @param onclick OnClick may contain javascript which should be executed on click. This is primarily used for WebAuthn.
 * @param pattern The input's pattern.
 * @param required Mark this input field as required.
 * @param `value` The input's value.
 */


interface UiNodeAttributes {

    /* Sets the input's disabled field to true or false. */
    @SerialName(value = "disabled") @Required val disabled: kotlin.Boolean
    /* The input's element name. */
    @SerialName(value = "name") @Required val name: kotlin.String
    /* NodeType represents this node's types. It is a mirror of `node.type` and is primarily used to allow compatibility with OpenAPI 3.0. In this struct it technically always is \"script\". */
    @SerialName(value = "node_type") @Required val nodeType: kotlin.String
    /* The script MIME type */
    @SerialName(value = "type") @Required val type: kotlin.String
    /* A unique identifier */
    @SerialName(value = "id") @Required val id: kotlin.String
    @SerialName(value = "text") @Required val text: UiText
    /* Height of the image */
    @SerialName(value = "height") @Required val height: kotlin.Long
    /* The script source */
    @SerialName(value = "src") @Required val src: kotlin.String
    /* Width of the image */
    @SerialName(value = "width") @Required val width: kotlin.Long
    /* The link's href (destination) URL.  format: uri */
    @SerialName(value = "href") @Required val href: kotlin.String
    @SerialName(value = "title") @Required val title: UiText
    /* The script async type */
    @SerialName(value = "async") @Required val async: kotlin.Boolean
    /* The script cross origin policy */
    @SerialName(value = "crossorigin") @Required val crossorigin: kotlin.String
    /* The script's integrity hash */
    @SerialName(value = "integrity") @Required val integrity: kotlin.String
    /* Nonce for CSP  A nonce you may want to use to improve your Content Security Policy. You do not have to use this value but if you want to improve your CSP policies you may use it. You can also choose to use your own nonce value! */
    @SerialName(value = "nonce") @Required val nonce: kotlin.String
    /* The script referrer policy */
    @SerialName(value = "referrerpolicy") @Required val referrerpolicy: kotlin.String
    /* The autocomplete attribute for the input. email InputAttributeAutocompleteEmail tel InputAttributeAutocompleteTel url InputAttributeAutocompleteUrl current-password InputAttributeAutocompleteCurrentPassword new-password InputAttributeAutocompleteNewPassword one-time-code InputAttributeAutocompleteOneTimeCode */
    @SerialName(value = "autocomplete") val autocomplete: UiNodeAttributes.Autocomplete?
    @SerialName(value = "label") val label: UiText?
    /* OnClick may contain javascript which should be executed on click. This is primarily used for WebAuthn. */
    @SerialName(value = "onclick") val onclick: kotlin.String?
    /* The input's pattern. */
    @SerialName(value = "pattern") val pattern: kotlin.String?
    /* Mark this input field as required. */
    @SerialName(value = "required") val required: kotlin.Boolean?
    /* The input's value. */
    @SerialName(value = "value") val `value`: kotlin.String?
    /**
     * The autocomplete attribute for the input. email InputAttributeAutocompleteEmail tel InputAttributeAutocompleteTel url InputAttributeAutocompleteUrl current-password InputAttributeAutocompleteCurrentPassword new-password InputAttributeAutocompleteNewPassword one-time-code InputAttributeAutocompleteOneTimeCode
     *
     * Values: EMAIL,TEL,URL,CURRENT_MINUS_PASSWORD,NEW_MINUS_PASSWORD,ONE_MINUS_TIME_MINUS_CODE
     */
    @Serializable
    enum class Autocomplete(val value: kotlin.String) {
        @SerialName(value = "email") EMAIL("email"),
        @SerialName(value = "tel") TEL("tel"),
        @SerialName(value = "url") URL("url"),
        @SerialName(value = "current-password") CURRENT_MINUS_PASSWORD("current-password"),
        @SerialName(value = "new-password") NEW_MINUS_PASSWORD("new-password"),
        @SerialName(value = "one-time-code") ONE_MINUS_TIME_MINUS_CODE("one-time-code");
    }
}

