/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package sh.ory.model

import sh.ory.model.UiNodeAttributes
import sh.ory.model.UiNodeMeta
import sh.ory.model.UiText

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Nodes are represented as HTML elements or their native UI equivalents. For example, a node can be an `<img>` tag, or an `<input element>` but also `some plain text`.
 *
 * @param attributes 
 * @param group Group specifies which group (e.g. password authenticator) this node belongs to. default DefaultGroup password PasswordGroup oidc OpenIDConnectGroup profile ProfileGroup link LinkGroup code CodeGroup totp TOTPGroup lookup_secret LookupGroup webauthn WebAuthnGroup passkey PasskeyGroup
 * @param messages 
 * @param meta 
 * @param type The node's type text Text input Input img Image a Anchor script Script
 */
@Serializable

data class UiNode (

    //@SerialName(value = "attributes") @Required val attributes: UiNodeAttributes,

    /* Group specifies which group (e.g. password authenticator) this node belongs to. default DefaultGroup password PasswordGroup oidc OpenIDConnectGroup profile ProfileGroup link LinkGroup code CodeGroup totp TOTPGroup lookup_secret LookupGroup webauthn WebAuthnGroup passkey PasskeyGroup */
    @SerialName(value = "group") @Required val group: UiNode.Group,

    @SerialName(value = "messages") @Required val messages: kotlin.Array<UiText>,

    @SerialName(value = "meta") @Required val meta: UiNodeMeta,

    /* The node's type text Text input Input img Image a Anchor script Script */
    @SerialName(value = "type") @Required val type: UiNode.Type

) {

    /**
     * Group specifies which group (e.g. password authenticator) this node belongs to. default DefaultGroup password PasswordGroup oidc OpenIDConnectGroup profile ProfileGroup link LinkGroup code CodeGroup totp TOTPGroup lookup_secret LookupGroup webauthn WebAuthnGroup passkey PasskeyGroup
     *
     * Values: DEFAULT,PASSWORD,OIDC,PROFILE,LINK,CODE,TOTP,LOOKUP_SECRET,WEBAUTHN,PASSKEY
     */
    @Serializable
    enum class Group(val value: kotlin.String) {
        @SerialName(value = "default") DEFAULT("default"),
        @SerialName(value = "password") PASSWORD("password"),
        @SerialName(value = "oidc") OIDC("oidc"),
        @SerialName(value = "profile") PROFILE("profile"),
        @SerialName(value = "link") LINK("link"),
        @SerialName(value = "code") CODE("code"),
        @SerialName(value = "totp") TOTP("totp"),
        @SerialName(value = "lookup_secret") LOOKUP_SECRET("lookup_secret"),
        @SerialName(value = "webauthn") WEBAUTHN("webauthn"),
        @SerialName(value = "passkey") PASSKEY("passkey");
    }
    /**
     * The node's type text Text input Input img Image a Anchor script Script
     *
     * Values: TEXT,INPUT,IMG,A,SCRIPT
     */
    @Serializable
    enum class Type(val value: kotlin.String) {
        @SerialName(value = "text") TEXT("text"),
        @SerialName(value = "input") INPUT("input"),
        @SerialName(value = "img") IMG("img"),
        @SerialName(value = "a") A("a"),
        @SerialName(value = "script") SCRIPT("script");
    }
}

