/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package sh.ory.model


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Update Login Flow with TOTP Method
 *
 * @param method Method should be set to \"totp\" when logging in using the TOTP strategy.
 * @param totpCode The TOTP code.
 * @param csrfToken Sending the anti-csrf token is only required for browser login flows.
 */
@Serializable

data class UpdateLoginFlowWithTotpMethod (

    /* Method should be set to \"totp\" when logging in using the TOTP strategy. */
    @SerialName(value = "method") @Required val method: kotlin.String,

    /* The TOTP code. */
    @SerialName(value = "totp_code") @Required val totpCode: kotlin.String,

    /* Sending the anti-csrf token is only required for browser login flows. */
    @SerialName(value = "csrf_token") val csrfToken: kotlin.String? = null

)

