/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package sh.ory.model


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Update Registration Flow with Profile Method
 *
 * @param method Method  Should be set to profile when trying to update a profile.
 * @param traits Traits  The identity's traits.
 * @param csrfToken The Anti-CSRF Token  This token is only required when performing browser flows.
 * @param screen Screen requests navigation to a previous screen.  This must be set to credential-selection to go back to the credential selection screen.
 * @param transientPayload Transient data to pass along to any webhooks
 */
@Serializable

data class UpdateRegistrationFlowWithProfileMethod (

    /* Method  Should be set to profile when trying to update a profile. */
    @SerialName(value = "method") @Required val method: kotlin.String,

    /* Traits  The identity's traits. */
    @SerialName(value = "traits") @Required val traits: kotlin.String,

    /* The Anti-CSRF Token  This token is only required when performing browser flows. */
    @SerialName(value = "csrf_token") val csrfToken: kotlin.String? = null,

    /* Screen requests navigation to a previous screen.  This must be set to credential-selection to go back to the credential selection screen. */
    @SerialName(value = "screen") val screen: kotlin.String? = null,

    /* Transient data to pass along to any webhooks */
    @SerialName(value = "transient_payload") val transientPayload: kotlin.String? = null

)

